baseurl = "https://www.example.com/" # Make sure to end baseurl with a '/'
title = "golab LIMS"
author = "Slingr"
# Shown in the side menu
copyright = "&copy; 2023. All rights reserved."
canonifyurls = true
paginate = 10
theme = 'blackburn'

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "golab app documentation"
  brand = "golab LIMS"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "02 Jan 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]

  [params.piwikAnalytics]
    siteid = 2
    piwikroot = "//analytics.example.com/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fas fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Platform"
    pre = "<i class='fas fa-sitemap fa-fw'></i>"
    weight = 2
    identifier = "platform"
    url = "/platform/"
  [[menu.main]]
    name = "Overview"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "platform-post-1"
    url = "/platform/post-1"
    parent = "platform"
  [[menu.main]]
    name = "Views"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "platform-post-2"
    url = "/platform/post-2"
    parent = "platform"
  [[menu.main]]
    name = "Mobile App"
    pre = "<i class='fas fa-mobile-alt fa-fw'></i>"
    weight = 3
    identifier = "mobile"
    url = "/mobile/"
  [[menu.main]]
    name = "Landing Page"
    pre = "<i class='fas fa-laptop fa-fw'></i>"
    weight = 4
    identifier = "landing"
    url = "/landing/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fas fa-envelope fa-fw'></i>"
    weight = 5
    identifier = "contact"
    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter="*"
  facebook="*"
  instagram="*"
  youtube="*"
  linkedin="*"
  github="yoshiharuyamashita"